
package br.com.pos.hotel.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservaService", targetNamespace = "http://services.hotel.pos.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.com.pos.hotel.services.Quarto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaQuartosDesocupados", targetNamespace = "http://services.hotel.pos.com.br/", className = "br.com.pos.hotel.services.GetListaQuartosDesocupados")
    @ResponseWrapper(localName = "getListaQuartosDesocupadosResponse", targetNamespace = "http://services.hotel.pos.com.br/", className = "br.com.pos.hotel.services.GetListaQuartosDesocupadosResponse")
    @Action(input = "http://services.hotel.pos.com.br/ReservaService/getListaQuartosDesocupadosRequest", output = "http://services.hotel.pos.com.br/ReservaService/getListaQuartosDesocupadosResponse")
    public List<Quarto> getListaQuartosDesocupados(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
