
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Passagens", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/ProjetoPOSIzaquiel/Passagens?WSDL")
public class Passagens
    extends Service
{

    private final static URL PASSAGENS_WSDL_LOCATION;
    private final static WebServiceException PASSAGENS_EXCEPTION;
    private final static QName PASSAGENS_QNAME = new QName("http://service/", "Passagens");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProjetoPOSIzaquiel/Passagens?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSAGENS_WSDL_LOCATION = url;
        PASSAGENS_EXCEPTION = e;
    }

    public Passagens() {
        super(__getWsdlLocation(), PASSAGENS_QNAME);
    }

    public Passagens(WebServiceFeature... features) {
        super(__getWsdlLocation(), PASSAGENS_QNAME, features);
    }

    public Passagens(URL wsdlLocation) {
        super(wsdlLocation, PASSAGENS_QNAME);
    }

    public Passagens(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PASSAGENS_QNAME, features);
    }

    public Passagens(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Passagens(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgenciaService
     */
    @WebEndpoint(name = "AgenciaServicePort")
    public AgenciaService getAgenciaServicePort() {
        return super.getPort(new QName("http://service/", "AgenciaServicePort"), AgenciaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgenciaService
     */
    @WebEndpoint(name = "AgenciaServicePort")
    public AgenciaService getAgenciaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AgenciaServicePort"), AgenciaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSAGENS_EXCEPTION!= null) {
            throw PASSAGENS_EXCEPTION;
        }
        return PASSAGENS_WSDL_LOCATION;
    }

}
