
package br.com.pos.hotel.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoInterno", targetNamespace = "http://services.hotel.pos.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoInterno {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addHotel", targetNamespace = "http://services.hotel.pos.com.br/", className = "br.com.pos.hotel.services.AddHotel")
    @ResponseWrapper(localName = "addHotelResponse", targetNamespace = "http://services.hotel.pos.com.br/", className = "br.com.pos.hotel.services.AddHotelResponse")
    @Action(input = "http://services.hotel.pos.com.br/ServicoInterno/addHotelRequest", output = "http://services.hotel.pos.com.br/ServicoInterno/addHotelResponse")
    public boolean addHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Hotel arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addQuarto", targetNamespace = "http://services.hotel.pos.com.br/", className = "br.com.pos.hotel.services.AddQuarto")
    @ResponseWrapper(localName = "addQuartoResponse", targetNamespace = "http://services.hotel.pos.com.br/", className = "br.com.pos.hotel.services.AddQuartoResponse")
    @Action(input = "http://services.hotel.pos.com.br/ServicoInterno/addQuartoRequest", output = "http://services.hotel.pos.com.br/ServicoInterno/addQuartoResponse")
    public boolean addQuarto(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Quarto arg1);

}
