
package com.pos.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocaService", targetNamespace = "http://services.pos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.pos.services.Carro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarrosDisponiveisPorIdLocadora", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetCarrosDisponiveisPorIdLocadora")
    @ResponseWrapper(localName = "getCarrosDisponiveisPorIdLocadoraResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetCarrosDisponiveisPorIdLocadoraResponse")
    @Action(input = "http://services.pos.com/LocaService/getCarrosDisponiveisPorIdLocadoraRequest", output = "http://services.pos.com/LocaService/getCarrosDisponiveisPorIdLocadoraResponse")
    public List<Carro> getCarrosDisponiveisPorIdLocadora(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onConstruct", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstruct")
    @ResponseWrapper(localName = "onConstructResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstructResponse")
    @Action(input = "http://services.pos.com/LocaService/onConstructRequest", output = "http://services.pos.com/LocaService/onConstructResponse")
    public void onConstruct();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "reservarCarro", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ReservarCarro")
    @ResponseWrapper(localName = "reservarCarroResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ReservarCarroResponse")
    @Action(input = "http://services.pos.com/LocaService/reservarCarroRequest", output = "http://services.pos.com/LocaService/reservarCarroResponse")
    public void reservarCarro(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Pessoa arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onDestroy", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroy")
    @ResponseWrapper(localName = "onDestroyResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroyResponse")
    @Action(input = "http://services.pos.com/LocaService/onDestroyRequest", output = "http://services.pos.com/LocaService/onDestroyResponse")
    public void onDestroy();

    /**
     * 
     * @return
     *     returns java.util.List<com.pos.services.Locadora>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLocadoras", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetLocadoras")
    @ResponseWrapper(localName = "getLocadorasResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetLocadorasResponse")
    @Action(input = "http://services.pos.com/LocaService/getLocadorasRequest", output = "http://services.pos.com/LocaService/getLocadorasResponse")
    public List<Locadora> getLocadoras();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.pos.services.Carro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarroPorId", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetCarroPorId")
    @ResponseWrapper(localName = "getCarroPorIdResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetCarroPorIdResponse")
    @Action(input = "http://services.pos.com/LocaService/getCarroPorIdRequest", output = "http://services.pos.com/LocaService/getCarroPorIdResponse")
    public Carro getCarroPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.pos.services.Carro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarrosDisponiveis", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetCarrosDisponiveis")
    @ResponseWrapper(localName = "getCarrosDisponiveisResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetCarrosDisponiveisResponse")
    @Action(input = "http://services.pos.com/LocaService/getCarrosDisponiveisRequest", output = "http://services.pos.com/LocaService/getCarrosDisponiveisResponse")
    public List<Carro> getCarrosDisponiveis();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.pos.services.Locadora
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLocadoraPorId", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetLocadoraPorId")
    @ResponseWrapper(localName = "getLocadoraPorIdResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.GetLocadoraPorIdResponse")
    @Action(input = "http://services.pos.com/LocaService/getLocadoraPorIdRequest", output = "http://services.pos.com/LocaService/getLocadoraPorIdResponse")
    public Locadora getLocadoraPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
